[package]
name = "sokoban-rs"
version = "0.3.1"
authors = ["Sébastien Watteau"]

[dependencies]
bitflags = "0.3.2"
clap = "1.3.0"
sdl2 = "0.8.0"
sdl2_image = "0.2.5"
sdl2_ttf = "0.6.1"
xml-rs = "0.1.25"

